extends SceneTree
const Content = preload("res://scripts/model/content_catalog.gd")
const Campaign = preload("res://scripts/model/campaign_catalog.gd")
func _init() -> void:
    Content.invalidate_cache()
    Campaign.invalidate_cache()
    var original = Content.new()
    var expected: Dictionary = original.wells.duplicate(true)
    original.wells.clear()
    assert(Content.new().wells == expected)
    var first = Campaign.new()
    assert(first.is_valid())
    var acts: Dictionary = first.acts.duplicate(true)
    var order: Array = first.act_order.duplicate()
    first.acts.clear()
    first.act_order.clear()
    var second = Campaign.new()
    assert(second.acts == acts and second.act_order == order)
    Content.invalidate_cache()
    Campaign.invalidate_cache()
    assert(Content.new().wells == expected)
    assert(Campaign.new().acts == acts)
    print("PASS catalog cache: isolated instances and explicit invalidation preserve definitions")
    quit()
